<?php

namespace AppBundle\Repository;

/**
 * JailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JailRepository extends \Doctrine\ORM\EntityRepository
{
}
