<?php

namespace AppBundle\Repository;

/**
 * JailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JailRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeOldRecords($id)
    {
        $update = $this->getEntityManager()->createQuery('
            DELETE FROM AppBundle:Jail j WHERE j.user = :id AND j.until <= :now
        ');

        return $update->execute([
            'now' => new \DateTime,
            'id' => $id
        ]);
    }
}
