<?php

namespace AppBundle\Repository;

/**
 * JailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JailRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeOldRecords($user)
    {
        $update = $this->getEntityManager()->createQuery('
            DELETE FROM AppBundle:Jail j WHERE j.user = :user AND j.until <= :now
        ');

        return $update->execute([
            'now' => new \DateTime,
            'user' => $user
        ]);
    }

    public function getActiveJail($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT j FROM AppBundle:Jail j WHERE j.user = :user AND j.until > :now')
            ->setParameter('user', $user)
            ->setParameter('now', new \DateTime)
            ->getOneOrNullResult()
        ;
    }
}
