<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOnlineOrderedByUsername()
    {
        $cutOff = new \DateTime();
        $cutOff->sub(new \DateInterval('PT10M'));

        return $this->getEntityManager()
            ->createQuery('SELECT u FROM AppBundle:User u WHERE u.lastOnline >= :cutOff ORDER BY u.username ASC')
            ->setParameter('cutOff', $cutOff)
            ->getResult()
        ;
    }

    public function updateLastOnline($id)
    {
        $update = $this->getEntityManager()->createQuery('
            UPDATE AppBundle:User u SET u.lastOnline = :now WHERE u.id = :id
        ');

        return $update->execute([
            'now' => new \DateTime,
            'id' => $id
        ]);
    }
}
