security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        main_provider:
            entity:
                class: AppBundle:User
                property: username

    access_control:
        - { path: ^/play, roles: ROLE_USER }
        - { path: ^/control, roles: ROLE_MOD }

    role_hierarchy:
        ROLE_MOD:   [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER, ROLE_MOD, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: public_home
                check_path: public_home
            provider: main_provider
            switch_user:
                role: ROLE_ADMIN
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
